[package]
name = "fibonacci"
version = "0.1.0"
authors = ["Kevin Gislason <kevingislason@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
